version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
  open-pull-requests-limit: 10
  reviewers:
  - caglarturali
  ignore:
  - dependency-name: react-markdown
    versions:
    - 5.0.3
    - 6.0.0
  - dependency-name: eslint
    versions:
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
    - 4.2.4
  - dependency-name: "@types/react-helmet"
    versions:
    - 6.1.0
    - 6.1.1
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
    - 11.2.5
    - 11.2.6
  - dependency-name: husky
    versions:
    - 5.0.4
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 6.0.0
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
    - 17.0.3
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
    - 17.0.3
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.3
